### ISSUE TITLE
VirusTotal - malicious 

### ISSUE THREAD

**Issue by modernman1** [bobranten/Ext4Fsd#52]
https://www.virustotal.com/gui/file/3c127f8e70c6b056a0185850efb71b9c45d2ff493b7df6b7b648eb89ec84214d

**Comment by bobranten** [comment]
Looks that you are right, I will need to clean the computer that was used 
and make a new installation program.

Bo Branten

**Comment by bobranten** [comment]
Could it be this explanation:
"The “malware scanners” often confuse the NSIS installer/uninstaller 
signatures as being malware, because some malware uses NSIS 
installer/uninstaller. When enough users vote the notepad++ executable or 
installer/uninstaller safe, such warnings usually go away."

I created an NSIS install program on an fresh installed Win 11 computer 
and I still got the warning "NSIS:MalwareX-gen"...

So parhaps we don't need to worry?

Bo Branten
